petStore:
  image: "jurosm/pet-store-api"
  internalPort: 80
  externalPort: 80
  replicaCount: 1
  postgres:
    password: "password"
    host: "pet-store.svc.cluster.local"
    name: "postgres"

  auth0:
    domain: ""
    audience: ""
    clientId: ""
    secret: ""
  stripe:
    secret: ""

petStoreWebApp:
  image: "jurosm/pet-store"
  internalPort: 4200
  externalPort: 80
  replicaCount: 1
  apiUrl: "http://localhost:5000"