apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-upload" $.Release.Namespace | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ $.Values.upload.externalPort }}
    targetPort: {{ $.Values.upload.internalPort }}
    protocol: TCP
    name: api-port
  selector:
    name: {{ printf "%s-upload" $.Release.Namespace | lower | quote }}