{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-web-app-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: 
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
      - localhost
      secretName: selfsigned-cert-tls
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: /upload(/|$)(.*)
          backend:
            service:
              name: {{ printf "%s-upload" $.Release.Namespace | lower }}
              port: 
                number: {{ $.Values.upload.externalPort }}
        - pathType: Prefix
          path: /social-web(/|$)(.*)
          backend:
            service:
              name: {{ printf "%s-social-web" $.Release.Namespace | lower }}
              port: 
                number: {{ $.Values.socialWeb.externalPort }}
{{- end -}}