{{- if $.Values.upload.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-upload" $.Release.Namespace | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      name: {{ printf "%s-upload" $.Release.Namespace | lower | quote }}
  replicas: {{ default 1 .Values.upload.replicaCount | int }}
  template:
    metadata:
      labels:
        name: {{ printf "%s-upload" $.Release.Namespace | lower | quote }}
        service: upload
    spec:
      containers:
      - name: "upload"
        image: {{ .Values.upload.image | quote }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.upload.internalPort | int }}
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: {{ .Values.upload.internalPort | int }}
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: {{ .Values.upload.internalPort | int }}
{{- end }}