apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-social-web" $.Release.Namespace | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ $.Values.socialWeb.externalPort }}
    targetPort: {{ $.Values.socialWeb.internalPort }}
    protocol: TCP
    name: api-port
  selector:
    name: {{ printf "%s-social-web" $.Release.Namespace | lower | quote }}