kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-social-web-conf" $.Release.Namespace | lower }}
  namespace: {{ $.Release.Namespace }}
data:
  DATABASE_URL: {{ printf "postgres://postgres:%s@postgres-database-postgresql.my-release-uros-namespace.svc.cluster.local/%s"  $.Values.socialWeb.db.password $.Values.socialWeb.db.name  }}
  JWT_SIGN_PRIVATE_KEY: {{ $.Values.socialWeb.jwtPrivateKey }}