kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-social-web-conf" $.Release.Namespace | lower }}
  namespace: {{ $.Release.Namespace }}
data:
  DATABASE_URL: {{ $.Values.socialWeb.db.url  }}
  JWT_SIGN_PRIVATE_KEY: {{ $.Values.socialWeb.jwtPrivateKey }}