upload:
  image: jurosm/upload-service
  internalPort: 8080
  replicaCount: 1
  enabled: true
  externalPort: 80
  storageClassName: standard

socialWeb:
  image: jurosm/social-web-service
  internalPort: 8000
  replicaCount: 1
  enabled: true
  externalPort: 80
  db:
    url: "postgres://postgres:password@mica-postgresdb.test.svc.cluster.local/socialweb"
  jwtPrivateKey: password
ingress:
  enabled: true

cert-manager:
  namespace: security
  installCRDs: true

postgresdb:
  global:
    postgresql:
      auth:
        postgresPassword: password
        database: socialweb