apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: {{ printf "%s-social-web" $.Release.Namespace | lower }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-social-web" $.Release.Namespace | lower }}
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi