apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
    kind: ClusterIssuer
  dnsNames:
    - localhost